#!/usr/bin/env bash


if [[ $(id -u) != 0 ]] && [[ -z $SUDO_COMMAND ]]; then
    echo 'run with sudo'
    exit
elif [[ ! -e /usr/share/archiso/ ]]; then
    echo 'archiso not installed'
    exit
fi

printf 'making working dir\n'
mkdir -p working_dir/out 2>/dev/null

cp -r /usr/share/archiso/configs/releng/* working_dir/

sed -e 's|^#.*||g' -e '/^$/d' my_pkgs >> working_dir/packages.x86_64

cp -r custom_root/* working_dir/airootfs/

rm working_dir/airootfs/mnt/{usb{1,2},mis,arch_install}/remove

cd working_dir || exit

printf 'building iso\n\n'
./build.sh -v
